### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by eileenfan** [marcosdiez/shareviahttp#40]
//package name: com.MarcosDiez.shareviahttp
//version: 2.0.5
//target sdk version: android-18
 android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.MarcosDiez.shareviahttp }
 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1632)
 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1424)
 	at android.app.Activity.startActivityForResult(Activity.java:3390)
 	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
 	at android.app.Activity.startActivityForResult(Activity.java:3351)
 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
 	at android.app.Activity.startActivity(Activity.java:3587)
 	at android.app.Activity.startActivity(Activity.java:3555)
 	at com.MarcosDiez.shareviahttp.activities.BaseActivity.rate_this_app(BaseActivity.java:216)
 	at com.MarcosDiez.shareviahttp.activities.BaseActivity.onOptionsItemSelected(BaseActivity.java:202)
 	at android.app.Activity.onMenuItemSelected(Activity.java:2566)
 	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:408)
 	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
 	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:113)
 	at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:69)
 	at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:206)
 	at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:776)
 	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
 	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:156)
 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
 	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
 	at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
 	at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
 	at android.view.View.performClick(View.java:4240)
 	at android.view.View$PerformClick.run(View.java:17721)
 	at android.os.Handler.handleCallback(Handler.java:730)
 	at android.os.Handler.dispatchMessage(Handler.java:92)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)

**Comment by eileenfan** [comment]
Maybe there's no Market apps like Google Play on the device, especially on emulator. Better to check it.

**Comment by StefMa** [comment]
@marcosdiez does the APK support different "install locations" than Play Store?
If not. This thing is really minor.
Anyway. Thanks for reporting @eileenfan!
